export default {
  REQUEST_SIGNUP: 'REQUEST_SIGNUP',
  RECEIVE_SIGNUP: 'RECEIVE_SIGNUP',
  REQUEST_LOGIN: 'REQUEST_LOGIN',
  RECEIVE_LOGIN: 'RECEIVE_LOGIN',
  LOGOUT: 'LOGOUT',

  REQUEST_ITEMS: 'REQUEST_ITEMS',
  RECEIVE_ITEMS: 'RECEIVE_ITEMS',
}
